name: ShanghaiEats
favicon: null
layout_spectrum: 0.10397920268587768
typography_spectrum: 0.9022309829015285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08548042993061244
  lightness: 0.44787299050949514
  saturation: 0.9522615855094045
  rhythmicContrast: 0.28534689848311245
purpose: []
